import 'package:flutter/material.dart';
import '../models/category.dart';

/// Top-level system category names mapped to logical icons.
const Map<String, IconData> _rootIcons = {
  'автомобиль': Icons.directions_car,
  'car': Icons.directions_car,
  'auto': Icons.directions_car,
  'банковское обслуживание': Icons.account_balance,
  'banking': Icons.account_balance,
  'bankwesen': Icons.account_balance,
  'banca': Icons.account_balance,
  'banque': Icons.account_balance,
  'banco': Icons.account_balance,
  'bankacılık': Icons.account_balance,
  'дети': Icons.child_friendly,
  'children': Icons.child_friendly,
  'kinder': Icons.child_friendly,
  'niños': Icons.child_friendly,
  'enfants': Icons.child_friendly,
  'bambini': Icons.child_friendly,
  'crianças': Icons.child_friendly,
  'çocuklar': Icons.child_friendly,
  'домашнее хозяйство': Icons.home,
  'household': Icons.home,
  'haushalt': Icons.home,
  'hogar': Icons.home,
  'домашние животные': Icons.pets,
  'pets': Icons.pets,
  'haustiere': Icons.pets,
  'mascotas': Icons.pets,
  'animaux': Icons.pets,
  'animali': Icons.pets,
  'animais': Icons.pets,
  'evcil hayvanlar': Icons.pets,
  'досуг и отдых': Icons.sports_esports,
  'leisure': Icons.sports_esports,
  'freizeit': Icons.sports_esports,
  'ocio': Icons.sports_esports,
  'loisirs': Icons.sports_esports,
  'tempo libero': Icons.sports_esports,
  'lazer': Icons.sports_esports,
  'eğlence': Icons.sports_esports,
  'коммунальные платежи': Icons.bolt,
  'utilities': Icons.bolt,
  'nebenkosten': Icons.bolt,
  'servicios': Icons.bolt,
  'charges': Icons.bolt,
  'utenze': Icons.bolt,
  'serviços públicos': Icons.bolt,
  'faturalar': Icons.bolt,
  'медицина': Icons.local_hospital,
  'medical': Icons.local_hospital,
  'medizin': Icons.local_hospital,
  'medicina': Icons.local_hospital,
  'santé': Icons.local_hospital,
  'salute': Icons.local_hospital,
  'saúde': Icons.local_hospital,
  'sağlık': Icons.local_hospital,
  'налоги, сборы и услуги': Icons.receipt_long,
  'taxes & fees': Icons.receipt_long,
  'образование': Icons.school,
  'education': Icons.school,
  'bildung': Icons.school,
  'educación': Icons.school,
  'éducation': Icons.school,
  'istruzione': Icons.school,
  'educação': Icons.school,
  'eğitim': Icons.school,
  'одежда, обувь, аксессуары': Icons.checkroom,
  'clothing & shoes': Icons.checkroom,
  'kleidung': Icons.checkroom,
  'ropa': Icons.checkroom,
  'vêtements': Icons.checkroom,
  'abbigliamento': Icons.checkroom,
  'roupas': Icons.checkroom,
  'giyim': Icons.checkroom,
  'clothing': Icons.checkroom,
  'одежда': Icons.checkroom,
  'обувь': Icons.checkroom,
  'аксессуары': Icons.watch,
  'sapatos': Icons.checkroom,
  'питание': Icons.restaurant,
  'food': Icons.restaurant,
  'essen': Icons.restaurant,
  'comida': Icons.restaurant,
  'alimentation': Icons.restaurant,
  'cibo': Icons.restaurant,
  'gıda': Icons.restaurant,
  'подарки, материальная помощь': Icons.card_giftcard,
  'gifts & donations': Icons.card_giftcard,
  'geschenke': Icons.card_giftcard,
  'regalos': Icons.card_giftcard,
  'cadeaux': Icons.card_giftcard,
  'regali': Icons.card_giftcard,
  'presentes': Icons.card_giftcard,
  'hediyeler': Icons.card_giftcard,
  'проезд, транспорт': Icons.directions_bus,
  'transport': Icons.directions_bus,
  'transportation': Icons.directions_bus,
  'verkehr': Icons.directions_bus,
  'trasporti': Icons.directions_bus,
  'transporte': Icons.directions_bus,
  'ulaşım': Icons.directions_bus,
  'прочие доходы': Icons.attach_money,
  'other income': Icons.attach_money,
  'sonstige einnahmen': Icons.attach_money,
  'otros ingresos': Icons.attach_money,
  'autres revenus': Icons.attach_money,
  'altri redditi': Icons.attach_money,
  'outros rendimentos': Icons.attach_money,
  'diğer gelirler': Icons.attach_money,
  'прочие личные расходы': Icons.more_horiz,
  'other expenses': Icons.more_horiz,
  'sonstige ausgaben': Icons.more_horiz,
  'otros gastos': Icons.more_horiz,
  'autres dépenses': Icons.more_horiz,
  'altre spese': Icons.more_horiz,
  'outras despesas': Icons.more_horiz,
  'diğer giderler': Icons.more_horiz,
  'расходы по работе': Icons.work,
  'business expenses': Icons.work,
  'связь, тв и интернет': Icons.wifi,
  'telecom & internet': Icons.wifi,
  'telekom & internet': Icons.wifi,
  'telecomunicaciones': Icons.wifi,
  'télécom & internet': Icons.wifi,
  'telecomunicazioni': Icons.wifi,
  'telecomunicações': Icons.wifi,
  'iletişim': Icons.wifi,
  'страхование': Icons.shield,
  'insurance': Icons.shield,
  'versicherung': Icons.shield,
  'seguros': Icons.shield,
  'assurance': Icons.shield,
  'assicurazione': Icons.shield,
  'seguro': Icons.shield,
  'sigorta': Icons.shield,
  'уход за собой': Icons.spa,
  'personal care': Icons.spa,
  'körperpflege': Icons.spa,
  'cuidado personal': Icons.spa,
  'soins personnels': Icons.spa,
  'cura personale': Icons.spa,
  'cuidados pessoais': Icons.spa,
  'kişisel bakım': Icons.spa,
  'персональные доходы': Icons.payments,
  'personal income': Icons.payments,
  'persönliches einkommen': Icons.payments,
  'ingresos personales': Icons.payments,
  'revenus personnels': Icons.payments,
  'reddito personale': Icons.payments,
  'rendimento pessoal': Icons.payments,
  'kişisel gelir': Icons.payments,
  'инвестиционный доход': Icons.trending_up,
  'investment income': Icons.trending_up,
  'kapitalerträge': Icons.trending_up,
  'ingresos de inversión': Icons.trending_up,
  "revenus d'investissement": Icons.trending_up,
  'reddito da investimenti': Icons.trending_up,
  'rendimento de investimento': Icons.trending_up,
  'yatırım geliri': Icons.trending_up,
  'инвестиционный расход': Icons.trending_down,
  'investment expense': Icons.trending_down,
  'investitionsausgaben': Icons.trending_down,
  'gasto de inversión': Icons.trending_down,
  "dépense d'investissement": Icons.trending_down,
  'spesa di investimento': Icons.trending_down,
  'despesa de investimento': Icons.trending_down,
  'yatırım gideri': Icons.trending_down,
  'проценты по кредитам и займам': Icons.percent,
  'loan interest': Icons.percent,
  'kreditzinsen': Icons.percent,
  'intereses de préstamos': Icons.percent,
  "intérêts d'emprunt": Icons.percent,
  'interessi su prestiti': Icons.percent,
  'juros de empréstimos': Icons.percent,
  'kredi faizi': Icons.percent,
  'вредные привычки': Icons.warning,
  'bad habits': Icons.warning,
  'schlechte gewohnheiten': Icons.warning,
  'malos hábitos': Icons.warning,
  'mauvaises habitudes': Icons.warning,
  'cattive abitudini': Icons.warning,
  'maus hábitos': Icons.warning,
  'kötü alışkanlıklar': Icons.warning,
  'мотоцикл': Icons.two_wheeler,
  'motorcycle': Icons.two_wheeler,
  'перевод': Icons.swap_horiz,
  'transfer': Icons.swap_horiz,
  'überweisung': Icons.swap_horiz,
  'transferencia': Icons.swap_horiz,
  'virement': Icons.swap_horiz,
  'trasferimento': Icons.swap_horiz,
  'transferência': Icons.swap_horiz,
  'не определена. для расходов': Icons.help_outline,
  'uncategorized expense': Icons.help_outline,
  'не определена. для доходов': Icons.help_outline,
  'uncategorized income': Icons.help_outline,
  'заработная плата': Icons.payments,
  'salary': Icons.payments,
  'gehalt': Icons.payments,
  'salario': Icons.payments,
  'salaire': Icons.payments,
  'stipendio': Icons.payments,
  'salário': Icons.payments,
  'maaş': Icons.payments,
  'топливо': Icons.local_gas_station,
  'fuel': Icons.local_gas_station,
  'kraftstoff': Icons.local_gas_station,
  'combustible': Icons.local_gas_station,
  'carburant': Icons.local_gas_station,
  'carburante': Icons.local_gas_station,
  'combustível': Icons.local_gas_station,
  'yakıt': Icons.local_gas_station,
  'такси': Icons.local_taxi,
  'taxi': Icons.local_taxi,
  'электричество': Icons.bolt,
  'electricity': Icons.bolt,
  'strom': Icons.bolt,
  'electricidad': Icons.bolt,
  'электроэнергия': Icons.bolt,
  'интернет и тв': Icons.wifi,
  'internet & tv': Icons.wifi,
  'бонусы и премии': Icons.card_giftcard,
  'bonuses': Icons.card_giftcard,
  'boni': Icons.card_giftcard,
  'дивиденды': Icons.trending_up,
};

/// Ordered keyword groups used as a fallback for custom/unknown categories.
const List<(String, IconData)> _keywordIcons = [
  ('инвестицион', Icons.trending_up),
  ('дивиденд', Icons.trending_up),
  ('акци', Icons.show_chart),
  ('мото', Icons.two_wheeler),
  ('авто', Icons.directions_car),
  ('машин', Icons.directions_car),
  ('топлив', Icons.local_gas_station),
  ('стоянк', Icons.directions_car),
  ('парковк', Icons.directions_car),
  ('гараж', Icons.garage),
  ('животн', Icons.pets),
  ('корм', Icons.pets),
  ('ветеринар', Icons.pets),
  ('дет', Icons.child_friendly),
  ('авиа', Icons.flight),
  ('поезд', Icons.train),
  ('метро', Icons.subway),
  ('такси', Icons.local_taxi),
  ('автобус', Icons.directions_bus),
  ('транспорт', Icons.directions_bus),
  ('билет', Icons.confirmation_number),
  ('еда', Icons.restaurant),
  ('продукт', Icons.local_grocery_store),
  ('ресторан', Icons.restaurant),
  ('кафе', Icons.local_cafe),
  ('обед', Icons.restaurant),
  ('питание', Icons.restaurant),
  ('алкоголь', Icons.liquor),
  ('сигарет', Icons.smoking_rooms),
  ('табак', Icons.smoking_rooms),
  ('вредн', Icons.warning),
  ('лекарств', Icons.medication),
  ('аптек', Icons.local_pharmacy),
  ('врач', Icons.medical_services),
  ('больниц', Icons.local_hospital),
  ('стомат', Icons.medical_services),
  ('медиц', Icons.local_hospital),
  ('одежд', Icons.checkroom),
  ('обувь', Icons.checkroom),
  ('аксессуар', Icons.watch),
  ('школ', Icons.school),
  ('универ', Icons.school),
  ('обучен', Icons.school),
  ('образован', Icons.school),
  ('учебник', Icons.menu_book),
  ('книг', Icons.menu_book),
  ('интернет', Icons.wifi),
  ('телефон', Icons.phone_android),
  ('связь', Icons.wifi),
  ('тв', Icons.tv),
  ('театр', Icons.theater_comedy),
  ('концерт', Icons.music_note),
  ('кино', Icons.movie),
  ('игр', Icons.sports_esports),
  ('развлечен', Icons.celebration),
  ('спорт', Icons.sports_soccer),
  ('фитнес', Icons.fitness_center),
  ('отдых', Icons.beach_access),
  ('досуг', Icons.sports_esports),
  ('хобби', Icons.palette),
  ('страхов', Icons.shield),
  ('подарк', Icons.card_giftcard),
  ('мебель', Icons.chair),
  ('уборо', Icons.cleaning_services),
  ('ремонт', Icons.home_repair_service),
  ('квартир', Icons.home),
  ('хозяйств', Icons.home),
  ('быт', Icons.home),
  ('дом', Icons.home),
  ('банк', Icons.account_balance),
  ('комисс', Icons.account_balance),
  ('налог', Icons.receipt_long),
  ('зарплат', Icons.payments),
  ('бонус', Icons.card_giftcard),
  ('преми', Icons.card_giftcard),
  ('работ', Icons.work),
  ('кредит', Icons.percent),
  ('займ', Icons.percent),
  ('процент', Icons.percent),
  ('подписк', Icons.subscriptions),
  ('сбережен', Icons.savings),
  ('накоплен', Icons.savings),
];

/// Resolves a logical Material icon for a category.
///
/// The icon is derived from the top-level parent category (system categories),
/// so every subcategory (e.g. all automotive ones) shares the same icon.
IconData categoryIconFor(Category category, {List<Category>? allCategories}) {
  final root = _rootCategory(category, allCategories ?? const <Category>[]);
  final byRoot = _rootIcons[root.name.trim().toLowerCase()];
  if (byRoot != null) return byRoot;

  final name = category.name.trim().toLowerCase();
  for (final (keyword, icon) in _keywordIcons) {
    if (name.contains(keyword)) return icon;
  }
  return Icons.category;
}

Category _rootCategory(Category category, List<Category> all) {
  var current = category;
  final seen = <String>{};
  while (current.parentId != null && current.parentId!.isNotEmpty && seen.add(current.id)) {
    Category? parent;
    for (final c in all) {
      if (c.id == current.parentId) {
        parent = c;
        break;
      }
    }
    if (parent == null) break;
    current = parent;
  }
  return current;
}
